Repository CachetHQ/Cachet, pull requests merged in 2018-06, with the labels that each got.

#3076 Schedules should be soft deletable
  app/Models/Schedule.php
  database/migrations/2018_06_14_201440_AlterSchedulesSoftDeletes.php
Labels: enhancement

#3085 Cleanup tests
  composer.json
  composer.lock
  tests/AbstractTestCase.php
  tests/Api/AbstractApiTestCase.php
  tests/Api/ComponentGroupTest.php
  tests/Api/ComponentTest.php
  tests/Api/GeneralTest.php
  tests/Api/IncidentTest.php
  tests/Api/IncidentUpdateTest.php
  tests/Api/MetricPointTest.php
  tests/Api/MetricTest.php
  tests/Api/ScheduleTest.php
  tests/Api/SubscriberTest.php
Labels: refactor

#3069 Fix the component group status
  app/Models/ComponentGroup.php
Labels: bug

#3094 Split Components and ComponentGroups into two controllers
  app/Http/Controllers/Dashboard/ComponentController.php
  app/Http/Controllers/Dashboard/ComponentGroupController.php
  app/Http/Routes/Dashboard/ComponentRoutes.php
Labels: refactor

#3098 Test for status changes before firing event
  app/Bus/Commands/Component/UpdateComponentCommand.php
  app/Bus/Handlers/Commands/Component/UpdateComponentCommandHandler.php
  app/Http/Controllers/Api/ComponentController.php
  tests/Api/ComponentTest.php
Labels: bug

#3100 Fix mail markdown notifications
  app/Notifications/Incident/NewIncidentNotification.php
  resources/lang/en/cachet.php
  resources/views/notifications/incident/new.blade.php
  resources/views/notifications/partials/subscription.blade.php
Labels: bug, refactor

#3113 Searchable tags
  app/Http/Controllers/Api/ComponentController.php
  app/Models/Component.php
  app/Models/Incident.php
  app/Models/Traits/HasTags.php
  app/Models/Traits/Taggable.php
Labels: feature

#3087 Fix how tags are created
  app/Bus/Commands/Tag/ApplyTagCommand.php
  app/Bus/Commands/Tag/CreateTagCommand.php
  app/Bus/Commands/Tag/DeleteTagCommand.php
  app/Bus/Commands/Tag/UpdateTagCommand.php
  app/Bus/Handlers/Commands/Tag/ApplyTagCommandHandler.php
  app/Bus/Handlers/Commands/Tag/CreateTagCommandHandler.php
  app/Bus/Handlers/Commands/Tag/DeleteTagCommandHandler.php
  app/Bus/Handlers/Commands/Tag/UpdateTagCommandHandler.php
  app/Http/Controllers/Api/ComponentController.php
  app/Http/Controllers/Dashboard/ComponentController.php
  resources/views/dashboard/components/edit.blade.php
  tests/Bus/Commands/Tag/ApplyTagCommandTest.php
  tests/Bus/Commands/Tag/CreateTagCommandTest.php
  tests/Bus/Commands/Tag/DeleteTagCommandTest.php
  tests/Bus/Commands/Tag/UpdateTagCommandTest.php
Labels: bug

#3092 Replace GrahamCampbell/Core
  app/Console/Commands/AppInstallCommand.php
  app/Console/Commands/AppResetCommand.php
  app/Console/Commands/AppUpdateCommand.php
  app/Console/Kernel.php
  app/Subscribers/CommandSubscriber.php
  composer.json
  config/app.php
Labels: refactor

#3093 Smoke Tests
  app/Http/Controllers/Api/GeneralController.php
  tests/SmokeTest.php
Labels: enhancement

#3126 Begin document about installation
  docs/installation.md
Labels: Documentation

#3103 Add notifications column to incidents
  app/Models/Incident.php
  database/migrations/2018_06_17_182507_AlterIncidentsAddNotifications.php
Labels: Enhancement
