Repository CachetHQ/Cachet, pull requests merged in 2019-01, with the labels that each got.

#3357 Improve database performance by removing duplicated queries and using eager loading
  app/Composers/DashboardComposer.php
  app/Foundation/Providers/ComposerServiceProvider.php
  app/Http/Controllers/Dashboard/ComponentController.php
  app/Http/Controllers/Dashboard/IncidentController.php
  app/Http/Controllers/StatusPageController.php
  app/Presenters/ComponentGroupPresenter.php
  app/Presenters/IncidentPresenter.php
  app/Presenters/UserPresenter.php
Labels: Enhancement, Refactor

#3433 Remove string about HTTP(s) for Piwik translation
  resources/lang/en/forms.php
Labels: Translations

#2931 Custom meta descriptions per incident
  app/Bus/Commands/Incident/CreateIncidentCommand.php
  app/Bus/Commands/Incident/UpdateIncidentCommand.php
  app/Bus/Handlers/Commands/Incident/CreateIncidentCommandHandler.php
  app/Bus/Handlers/Commands/Incident/UpdateIncidentCommandHandler.php
  app/Bus/Handlers/Traits/StoresMeta.php
  app/Http/Controllers/Dashboard/IncidentController.php
  resources/lang/en/forms.php
  resources/views/dashboard/incidents/add.blade.php
  resources/views/dashboard/incidents/edit.blade.php
  resources/views/layout/master.blade.php
  resources/views/single-incident.blade.php
  tests/Bus/Traits/StoresMetaTest.php
  tests/Functional/Incident/MetaSeoTest.php
Labels: Feature
