Repository CachetHQ/Cachet, pull requests merged in 2019-02, with the labels that each got.

#3450 Do not use arr_* or str_* helpers
  app/Composers/StatusComposer.php
  app/Composers/TimezoneLocaleComposer.php
  app/Foundation/Exceptions/Filters/ApiFilter.php
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/Dashboard/ComponentController.php
  app/Http/Controllers/Dashboard/UserController.php
  app/Http/Controllers/SetupController.php
  app/Integrations/Core/Beacon.php
  app/Models/Invite.php
  app/Models/Subscriber.php
  app/Models/User.php
  tests/Api/ScheduleTest.php
Labels: Refactor

#3462 We no longer need the dev symfony requirements
  composer.json
  composer.lock
Labels: dependencies

#3494 Correctly retrieve the value from metrics
  app/Repositories/Metric/AbstractMetricRepository.php
Labels: Bug, Metrics
