Repository CachetHQ/Cachet, pull requests merged in 2019-07, with the labels that each got.

#3402 Authenticate with REMOTE_USER
  app/Foundation/Providers/RouteServiceProvider.php
  app/Http/Kernel.php
  app/Http/Middleware/RemoteUserAuthenticate.php
Labels: Authentication, Feature, Help Wanted

#3661 Fix validation of metric thresholds
  app/Http/Controllers/Dashboard/MetricController.php
  app/Models/Metric.php
Labels: Bug, Metrics

#3619 upgraded google2fa (0.7->5.0)
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/Dashboard/UserController.php
  composer.json
  composer.lock
  config/app.php
  resources/views/dashboard/user/index.blade.php
Labels: Refactor

#3704 Improved Tags Management
  app/Bus/Commands/Component/CreateComponentCommand.php
  app/Bus/Commands/Component/UpdateComponentCommand.php
  app/Bus/Commands/Tag/ApplyTagCommand.php
  app/Bus/Commands/Tag/CreateTagCommand.php
  app/Bus/Commands/Tag/DeleteTagCommand.php
  app/Bus/Commands/Tag/UpdateTagCommand.php
  app/Bus/Handlers/Commands/Component/CreateComponentCommandHandler.php
  app/Bus/Handlers/Commands/Component/UpdateComponentCommandHandler.php
  app/Bus/Handlers/Commands/Tag/ApplyTagCommandHandler.php
  app/Bus/Handlers/Commands/Tag/CreateTagCommandHandler.php
  app/Bus/Handlers/Commands/Tag/DeleteTagCommandHandler.php
  app/Bus/Handlers/Commands/Tag/UpdateTagCommandHandler.php
  app/Http/Controllers/Api/ComponentController.php
  app/Http/Controllers/Dashboard/ComponentController.php
  app/Models/Tag.php
  app/Models/Taggable.php
  app/Models/Traits/HasTags.php
  app/Presenters/ComponentPresenter.php
  database/migrations/2018_04_02_163658_MigrateComponentTagTable.php
  tests/Api/ComponentTest.php
  tests/Bus/Commands/Component/CreateComponentCommandTest.php
  tests/Bus/Commands/Component/UpdateComponentCommandTest.php
  tests/Bus/Commands/Tag/ApplyTagCommandTest.php
  tests/Bus/Commands/Tag/CreateTagCommandTest.php
  tests/Bus/Commands/Tag/DeleteTagCommandTest.php
  tests/Bus/Commands/Tag/UpdateTagCommandTest.php
  tests/Models/TaggableTest.php
Labels: Refactor, Tags
